const listItems = [
  {
    id: "101",
    name: "Ping Pong",
    img: "images/GameHub_covers.jpg",
    price: 49.0,
    priceold: 59.99,
    category: "sport",
  },
  {
    id: "102",
    name: "Super duper",
    img: "images/GameHub_covers2.jpg",
    price: 35.0,
    priceold: 49.99,
    category: "adventure",
  },
  {
    id: "103",
    name: "Black",
    img: "images/GameHub_covers3.jpg",
    price: 39.0,
    priceold: 49.99,
    category: "action",
  },
  {
    id: "104",
    name: "Furious",
    img: "images/GameHub_covers4.jpg",
    price: 25.0,
    priceold: 49.99,
    category: "action",
  },
  {
    id: "105",
    name: "Assasin",
    img: "images/GameHub_covers5.jpg",
    price: 45.0,
    priceold: 49.99,
    category: "action",
  },
  {
    id: "106",
    name: "Space war",
    img: "images/GameHub_covers6.jpg",
    price: 38.0,
    priceold: 49.99,
    category: "strategy",
  },
];
